### ISSUE TITLE
Add External Urls to Details Page

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1006]
See ticket #887 for word document

- [ ] list external urls on details page

**Comment by bferguso** [comment]
Took a bit longer due to link click being blocked by arches core somewhere. There is some strange pointer behaviour - if hovering on the left side of the URL it doesn't show the pointer, but hovering toward the right side of the URL it does. Putting this in a separate branch for now until a decision is made whether or not to include this feature as part of the this release. Seeing some security warning on at least one partner's website (Burnaby - DhRr-62).

Added an underline on hover to match the behaviour in the results card links.

**Comment by emjohnst** [comment]
Done in test
