### ISSUE TITLE
BCHP Not Working on Legacy

### ISSUE THREAD

**Issue by IJGoldie** [bcgov/BCHeritage#132]

**Comment by bferguso** [comment]
There is an issue with spatial import of CSV that is causing the point coordinates to be transposed so all spatial data fails to import. Worked around it by loading data in DEV instance and uploading using the arches export/import business data function.

Have sent a request to the community to see if someone else has seen this transposition issue. Will address root cause in a separate ticket.

Also fixed issues caused by arches core updates causing map popup functionality to fail.

BCRHP on Legacy now functioning.

FYI @IJGoldie
