### ISSUE TITLE
Resource Model Header Name Changes

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#230]
suggested changes outlined in an excel and emailed

**Comment by bferguso** [comment]
Questions:
1. What should the `Other Fossil Type` label be changed to? `Other Scientific Name`? Something else?

**Comment by LeannePyle** [comment]
Let's discuss- If Fossil Type Name is going to be a full binomial name of genus and species = Scientific Name, then not sure that "Other Fossil Type" is necessary? If the first field is just the genus name, then the second field would be needed for species choice.

**Comment by bferguso** [comment]
Another question - you've changed the Significant & Non-significant value to "Significant Fossils Present". Do you want to be able to distinguish between entries that have non-significant fossil names and either barren samples or samples with only common names? The change made does not allow for distinguishing that.

**Comment by bferguso** [comment]
Model changes to make::
- [ ] Significance checkbox at fossil, sample and collection event levels
- [ ] Significance Ranking code at Site level
- [ ] Significance Details at all levels (only visible when significant)
- [ ] No need to distinguish between common (non-significant) and unknown/not overridden

**Comment by bferguso** [comment]
@LeannePyle , @elisabethdeom  - A couple more questions:
- [ ] How do we want to handle the significance ranking code (Low, Very High) that is currently in each row? My understanding is that this should be only appled at the site level? Do we also want to capture this at the Collection Event level for historical data?
- [ ] How are we going to deal with the data conversion of the Common Names? In the model we've determined that only 1 common name can be applied for each fossil type found in a Fossil Sample, however multiples are associated with each fossil type because lists were allowed in Significant Scientific, Non-Significant Scientific and Common Names.

**Comment by LeannePyle** [comment]
--suggest yes to applying the code at site level but yes also to collection event level for historical data to capture all point data where there may be just one fossil/one site
--some instances may have just one fossil specimen that has one common name. There are many instances where multiple common names need to stay together as a list of things that co-occur in a sample but where maybe only one primary specific fossil was named scientifically - let's discuss.  Could these secondary or accessory common fossil names be listed for the historical data?

**Comment by bferguso** [comment]
- [ ] Add a free-form text field for Fossil Part  `Other Fossil Part or Fossil Part Details` 40 chars
- [ ] Add a free-form text field for Trace Fossil `Other Trace Fossil  or Trace Fossil Details` 40 chars
- [ ] Add a free-form text field for the BC Fossil Identification 80 chars

**Comment by bferguso** [comment]
@LeannePyle - Please list fossil notes that should be looked up.
- [ ] Note value

**Comment by LeannePyle** [comment]
Two scientific names that were in the Existing notes column:
Occidentalis sp.
Parallelodont simillima
