### ISSUE TITLE
Colour schemes for maps

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#500]
upload new schemes to see what the changes will look like

**Comment by bferguso** [comment]
Comments of initial scheme:
- Storage locations colour is hard to see on BC Roads base map
- Trim contours - there are 2 elevations to consider - 20m and 100m. Currently using light grey for 20m and darker grey for 100m. This layer should be a line-only layer, not a fill otherwise it will cover 100% of the map
- Parks - there are protection types we need to consider
- FRPC BR & Overburden - There are 4 types we need to consider from High , Medium, Low and Very low
- Bedrock Geology - there are multiple values to consider: intrusive rocks, metamorphic rocks, sedimentary rocks, ultramafic rocks, volcanic rocks
- Regional / Municipal boundaries - fill might be too much for these as they tend to cover large amounts of the map

**Comment by rajpersram** [comment]
I'll update and upload a revision 1 version of the colour scheme. 

Do you know what the protection types for Parks?  

Is FRPC BR (what is 'BR') one layer, while FRPC Overburden is another? Will each need 4 types, totalling 8 altogether? 

I'll look into what kind of geological rock types we can adopt, trying to stay true to [standards](https://uhlibraries.pressbooks.pub/app/uploads/sites/6/2019/05/ClassifyingSedRocks-v2-scaled.jpg). If you have any additional references or a library for what types of shading (lines, curves, plus sign), please let me know.

**Comment by purewm** [comment]
I have updated all the colour schemes mentioned above, documented in Teams > Fossils > BC Gov Fossils Management System Color Scheme r1.docx. Have also updated the maps directly via the Service Styling submenu on Legacy. 

Please check on FRPC BR json to ensure it's referring to the proper map, as I had to try to recover the original which was overwritten by FRPC Overburden. I tried to change the references from ovb to br throughout the JSON file to fix. Many apologies for that!

**Comment by bferguso** [comment]
@LeannePyle, @elisabethdeom - please let me know when you've had time to review Legacy and I'll pull those changes into the codebase.

@purewm - I've fixed the FRPC BR layer - there were a bunch of un-parseable colour values like `"rgba(100,0,100,0,.2)"` (with different values for the 100) which I assumed to be `"rgba(100,0,100,.2)"`, removing the last `,0`. If that's not the case please update to the intended value.
