### ISSUE TITLE
Add Registration Status to Search Result Card

### ISSUE THREAD

**Issue by KatieMcEvoy** [bcgov/BCHeritage#636]
- [x] Remove Borden Number from search result card
- [x] Add Registration Status to search result card - ensure the status can fit on one line for easy readability - perhaps forgo label and just add the statues "Registered" "Cancelled" "Legacy" 'Federal Jurisdiction" if it exceeds one line.

**Comment by bferguso** [comment]
Let's play around with the font sizes and weight in one of our upcoming meetings to see if we can resolve it that way. Also need feedback about whether we want to change the Card/popup layout to be Label above value as Raj had recommended.

**Comment by emjohnst** [comment]
@bferguso are you free tomorrow or thursday afternoon to go over this. You mention Raj's specification in this ticket and another ticket. Can you point out those changes on our next call?

**Comment by emjohnst** [comment]
Now that Borden numbers are included in details cards following site name this issue is less pressing for mvp, removing label

**Comment by emjohnst** [comment]
@bferguso to make this less of an issue I'm suggesting the following changes and will update description of ticket: let's remove Borden number from search results card since it is now in site name and on map. Let's also add Registration Status to search result card instead because some sites have duplicate records and it is impossible to tell from the search results panel if one of those records is already cancelled or if the site has legacy status, etc.

**Comment by bferguso** [comment]
Need to run an ES reindex for the heritage_sites resource model after this PR is done.

**Comment by emjohnst** [comment]
Done in test
