### ISSUE TITLE
Advanced Search Error

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#767]
When adding more than three search cards of the same field (for example Legislative Act) under Advanced Search there is an error pop up saying "Request Failed... Expecting value: line 1 column 1 (char 0)"

**Comment by bferguso** [comment]
This is caused by an enhancement which allowed filter by complex geometries which generated very large URLs. This was originally observed in IE which has approx. 5000 character URL limit. Technically the limit should be 2000 which is what the original fix implemented, but this is quite small and Advanced Search in Arches Core doesn't allow for it. Increased this limit to 35,000 characters which many browsers support. Edge 16 apparently supports about 10,000. We'll need to keep an eye on this and handle Edge if we start bumping into this limit.

**Comment by bferguso** [comment]
Please ensure you do a hard refresh with your browser prior to testing as this has javascript updates.

**Comment by emjohnst** [comment]
@bferguso this is better but we can still only add up to 6 cards (municipal designations have 7 legislative acts)(to search all provincial sites is 11 cards). I think searching # of designations would work a lot better for us if we applied a drop down list of "types" or "labels" in Official recognition details  so that we could search by "Municipal" and "Designation" and that label could also be used for the details card, public facing site, etc. to simplify what kind of site it is

**Comment by KatieMcEvoy** [comment]
Above issue persists.

**Comment by bferguso** [comment]
This is a browser limitation. This will require a rework of the advanced search / overall search functionality in Arches. I'd suggest we live with it as is for now as this is a larger issue with Arches Core.

**Comment by emjohnst** [comment]
Accepting issue for now.
