### ISSUE TITLE
Weird CSV Results

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#829]
Description
Some sites are not exporting to the CSV with data in the right fields. Can you look into why this might be happening for specific sites? The two sites I was able to identify this happening to are below, but there could be more:
DiRs-123
DiRt-43

[Heritage Site 22.csv](https://github.com/bcgov/BCHeritage/files/14212976/Heritage.Site.22.csv)

Steps to reproduce
1. Search either site by borden number above
2. Go to Download Icon
3. Select CSV
4. Click Download and view
		
Actual Results
Results should be formatted to CSV columns
		
Expected Results
Results carry over to two lines, excess of spatial information, information does not line up with Columns

**Comment by bferguso** [comment]
This CSV opens fine with Neo Office. This may be an excel import issue. It (may?) be caused by the massive geometry. I wonder if it makes sense to remove the spatial data from the export so it isn't in the CSV file. If we want to try that we need to confirm that a shape file will still export properly

**Comment by emjohnst** [comment]
@bferguso  I tried to remove the spatial data from export and that did resolve the csv issue but then I was not able to export a shapefile. If we build custom reports post mvp will that resolve the issue?

**Comment by emjohnst** [comment]
This might be resolved with latest csv export. Will do more testing and re-open new ticket if issue still persists.
