### ISSUE TITLE
Add satellite imagery layer

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#889]
Could be Post-MVP 2

**Comment by bferguso** [comment]
@emjohnst - I'll need information about the satellite imagery source to complete this.

**Comment by emjohnst** [comment]
@bferguso we will have to schedule a time for me to log into ArcGIS online, and for us to walk through these steps: https://developers.arcgis.com/documentation/mapping-apis-and-services/security/tutorials/create-and-manage-an-api-key/
This is the map imagery I'd like to use: https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9

**Comment by emjohnst** [comment]
From Jason from Esri: While not a WMS layer, it is still OGC compliant as a WMTS. Hopefully this is what she means:
[https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/WMTS/1.0.0/WMTSCapabilities.xml](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fservices.arcgisonline.com%2Farcgis%2Frest%2Fservices%2FWorld_Imagery%2FMapServer%2FWMTS%2F1.0.0%2FWMTSCapabilities.xml&data=05%7C01%7CSonia.M.Fernandes%40gov.bc.ca%7C08dedf68c4014f06a39b08dbf6b72f20%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638375038855146792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8A%2Bd6VYKNR7CJ6%2FsAW%2F48EziXkQVg20ZGNSzaElCYiE%3D&reserved=0)

If at all possible, she should be using Rest Service endpoint. If they have built custom app, they can use our leaflet to call the basemap
[https://developers.arcgis.com/documentation/mapping-apis-and-services/maps/services/basemap-layer-service/#image-tile-service-url](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopers.arcgis.com%2Fdocumentation%2Fmapping-apis-and-services%2Fmaps%2Fservices%2Fbasemap-layer-service%2F%23image-tile-service-url&data=05%7C01%7CSonia.M.Fernandes%40gov.bc.ca%7C08dedf68c4014f06a39b08dbf6b72f20%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638375038855146792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=alKxKgP8cHXTyEWyDVjyKGAZrbPlI1yOqVD1k9alE2E%3D&reserved=0)

It is free to use up to 2M tile transactions/month [https://developers.arcgis.com/pricing/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopers.arcgis.com%2Fpricing%2F&data=05%7C01%7CSonia.M.Fernandes%40gov.bc.ca%7C08dedf68c4014f06a39b08dbf6b72f20%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638375038855146792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6MfPVzwThufvaIV8a0%2B8sFJdFlwgDqtOG3S7ZZQU0I8%3D&reserved=0)
For casual use that should be good enough. Otherwise, she’ll have to pay for the API or use an AGO subscription named user.

**Comment by emjohnst** [comment]
Closing in favour of #611
