### ISSUE TITLE
KML file Issue

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#900]
Able to add but unable to save KML file for trail.

Steps:
1. Converted Shapefile to KML file in ArcGIS
2. Uploaded KML file to Spatial Location in Heritage Site Resource Model
3. Clicked Add

Actual Result: Error appeared - Unable to Save (see attached image)

Expected Result: Spatial Location card should be added 

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/6eb341b7-fc96-47da-a3b1-7b2301c5a6ed)

**Comment by bferguso** [comment]
@emjohnst - Can you please send me the KML file?

**Comment by bferguso** [comment]
This appears to be caused by the size of the geometry - this is the error on the server:
```
None - Geometry has too many coordinates for Elasticsearch (5385),                         
Please limit to less then 1500 coordinates of 5 digits of precision or less.. This data was not imported.
```

There were approximately 5800 points in the geometry. I increased the limit in my Dev instance to 6500 and was able to import the geometry successfully.

Opened an issue in Arches Core to address issue: https://github.com/archesproject/arches/issues/10656

**Comment by bferguso** [comment]
This is superseded by #969.
