### ISSUE TITLE
Heritage Sites not Loading

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#922]
Two site records will not load Details Page from search results and will not load record pages:

Uphill Neighbourhood - DiQh-68
Nelson Street Grids - DjQh-20

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/2d82ecf4-3d82-43be-8bed-746f0f376f21)

**Comment by bferguso** [comment]
This is likely due to the size of those records. The httpd server CPU is pinned at 100%. ~Wondering if we should restart the httpd server to see if that unblocks the process.~
The httpd server finally became idle. I was able to bring up the DjQh-20 report and details tab, and there is a huge geometry as well as hundreds of  addresses associated with it. We may need to look at how we are handling these large sites as there could be significant performance issues if these types of sites are continually accessed.

I was also able to bring up DiQh-68 which took even longer than DjQh-20 (5-10 minutes). This site has an even larger number of legal addresses, which is the cause of the delay.

**Comment by emjohnst** [comment]
@bferguso  Also experienced a 5+ minute delay for site Telegraph Trail - FhRm-15.

I think we have a quite a few large sites that are having issues opening. I'm hoping we can resolve this for the public site launch.

**Comment by emjohnst** [comment]
Resolved in test
