### ISSUE TITLE
Wrong Images Associated with Site

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#926]
FgRj-12 has two images added to the record in no way related to the site. Wondering how these images were associated and uploaded to the site and if this is an isolated occurrence, or is there a chance this happened to more sites? No images were associated with this site in HRIA.

**Comment by bferguso** [comment]
The images being displayed were in the `F/g/R/j/12` image directory in HRIA which is why they are associated with this record. This was an issue previously identified as an issue that some of the files seemed to be mis-categorized in HRIA. It is possible this could be the case with other images as well if there were others that were mis-categorized in HRIA.

**Comment by emjohnst** [comment]
@bferguso also found miscategorized images with DfRv-136. Is there a way to identify what images might have been miscategorized? I have concerns about going to the public with random images appearing on site records.

**Comment by emjohnst** [comment]
As discussed, this will have to be manually resolved.
