### ISSUE TITLE
Fossil Type and Reported Fossil details card is empty

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#936]
clicking Details on search card brings up empty card

**Comment by bferguso** [comment]
@LeannePyle - Nothing has been specified for the details page for these two resource instance types. Please specify which attributes you'd like displayed and we'll implement. Also -  please create a separate ticket for Fossil Type and Reported Fossil. Is Reported Fossil necessary for MVP since we won't be letting the public submit those yet anyway?

**Comment by bferguso** [comment]
Closing this as separate issues have been created to define what should be on the details tab for these resource types.
